//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeorgeBrownTeacher_CourseManagement.Business_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegistrationID { get; set; }
        public string CourseNumber { get; set; }
        public int TeacherID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
